iio-private.h: Increase MAX_ATTR_VALUE
This limit was arbitrarily chosen. Prior in truncating the string,
it got parsed by libini, processed by xmlEncodeEntitiesReentrant().
So we know it is zero terminated and a valid string.
Keep a limit by increase it by 8x. Hopefully no valid use case will ever
exceed this limit.

This fixes a regression on M2k where the temperature calibration values
attribute exceeds 4k.

ERROR: Internal libIIO error: iio_context_create_xml str length issue
ERROR: Unable to create local context: Cannot allocate memory (12)


Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>