cmake: ensure WITH_AIO=0 and WITH_IIOD_USBD=1 fails
at cmake time, not at link time.

Turns this:
/usr/bin/ld: CMakeFiles/iiod.dir/iiod.c.o: in function `main':
/home/benja/git/libiio/iiod/iiod.c:531: undefined reference to `start_usb_daemon'
[100%] Built target iio_stresstest
collect2: error: ld returned 1 exit status
make[2]: *** [iiod/CMakeFiles/iiod.dir/build.make:227: iiod/iiod] Error 1
make[1]: *** [CMakeFiles/Makefile2:466: iiod/CMakeFiles/iiod.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target iio_attr
make: *** [Makefile:136: all] Error 2

into this:
CMake Error at iiod/CMakeLists.txt:72 (message):
  Sorry, USB support in iiod (WITH_IIOD_USBD) requires async I/O support
  (WITH_AIO)

should resolve #984

Signed-off-by: Robin Getz <rgetz@mathworks.com>