iio-monitor: Add missing includes and define _BSD_SOURCE
Add missing include files as well as _BSD_SOURCE. Fixes the following
warnings:

	iio-monitor.c: In function ‘read_thd’:
	iio-monitor.c:90:3: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
	   usleep(100000);
	   ^
	iio-monitor.c: In function ‘show_main_screen’:
	iio-monitor.c:177:3: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
	   dev_names[i] = strdup(buf);
	   ^
	iio-monitor.c:177:16: warning: assignment makes pointer from integer without a cast
	   dev_names[i] = strdup(buf);

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>