iio.py: fix Trigger instantiation
Trigger() is being passed device contents, but no context, and therefore
fails like so:

|>>> adc._ctrl.trigger
|Traceback (most recent call last):
|  File "<stdin>", line 1, in <module>
|  File "/home/baylibre/git/pyadi-iio/venv/lib/python3.10/site-packages/iio.py", line 1281, in _get_trigger
|    trig = Trigger(value.contents)
|TypeError: Trigger.__init__() missing 1 required positional argument: '_device'

Pass self.ctx as the first argument so that the trigger is properly
instantiated.

Fixes #1107.

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>