fix #336, remove warnings on FreeBSD
Previously, building libiio on FreeBSD would warn with:
network.c:240:8: warning: implicit declaration of function 'pipe2' is invalid in C99

This fixes that for all BSDs, since pipe2 (inside <unistd.h>) is protected by __BSD_VISIBLE.
On Linux, it's protected by _GNU_SOURCE (which is already defined in the cmake).

Signed-off-by: Robin Getz <robin.getz@analog.com>