This is a small tweak to try to reduce the travis-ci noise
today, we get errors like:

running install
Traceback (most recent call last):
  File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 89, in <module>
    setup(**config)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 43, in run
    self._check_libiio_installed()
  File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 66, in _check_libiio_installed
    raise Exception(msg)
Exception: The libiio library could not be found.
            libiio needs to be installed first before the python bindings.
            The latest release can be found on GitHub:
            https://github.com/analogdevicesinc/libiio/releases

Since the libiio isn't installed or on path during the make package
step. This commit does that.

Signed-off-by: Robin Getz <robin.getz@analog.com>